# Generated by Django 5.0 on 2023-12-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='photo_samples_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
