# Generated by Django 5.0 on 2023-12-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_attendance_photo_samples_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='photo_samples_status',
        ),
        migrations.AddField(
            model_name='student',
            name='photo_samples_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
