# Generated by Django 5.0 on 2023-12-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_attendance_course_alter_attendance_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Roll',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
